default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials.postgres_user %>
  password: <%= Rails.application.credentials.postgres_password %>
  pool: 5
  timeout: 5000
  host: <%= Rails.application.credentials.postgres_host %>

development:
  <<: *default
  database: <%= Rails.application.credentials.postgres_db %>

test:
  <<: *default
  database: <%= Rails.application.credentials.postgres_test_db %>

production:
  <<: *default
  host: <%= Rails.application.credentials.db_host %>
  database: <%= Rails.application.credentials.db_database %>
  username: <%= Rails.application.credentials.db_username %>
  password: <%= Rails.application.credentials.db_password %>